// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.test.grpcTest.grpc_api;

public final class Grpc {
  private Grpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UnaryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UnaryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UnaryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UnaryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\"Y\n\014UnaryRequest\022\023\n\013serviceN" +
      "ame\030\001 \001(\t\022\022\n\nmethodName\030\002 \001(\t\022\014\n\004data\030\003 " +
      "\001(\014\022\022\n\nrequest_id\030\004 \001(\t\"Z\n\rUnaryResponse" +
      "\022\023\n\013serviceName\030\001 \001(\t\022\022\n\nmethodName\030\002 \001(" +
      "\t\022\014\n\004data\030\003 \001(\014\022\022\n\nrequest_id\030\004 \001(\t2@\n\013G" +
      "rpcService\0221\n\020SendUnaryRequest\022\r.UnaryRe" +
      "quest\032\016.UnaryResponseB$\n\032com.test.grpcTe" +
      "st.grpc_apiB\004GrpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_UnaryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UnaryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UnaryRequest_descriptor,
        new java.lang.String[] { "ServiceName", "MethodName", "Data", "RequestId", });
    internal_static_UnaryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_UnaryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UnaryResponse_descriptor,
        new java.lang.String[] { "ServiceName", "MethodName", "Data", "RequestId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
