// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.test.grpcTest.grpc_api;

public interface UnaryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnaryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string serviceName = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>optional string serviceName = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>optional string methodName = 2;</code>
   */
  java.lang.String getMethodName();
  /**
   * <code>optional string methodName = 2;</code>
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <code>optional bytes data = 3;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>optional string request_id = 4;</code>
   */
  java.lang.String getRequestId();
  /**
   * <code>optional string request_id = 4;</code>
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();
}
