// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.test.grpcTest.grpc_api;

public interface UnaryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UnaryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string serviceName = 1;</code>
   */
  java.lang.String getServiceName();
  /**
   * <code>optional string serviceName = 1;</code>
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>optional string methodName = 2;</code>
   */
  java.lang.String getMethodName();
  /**
   * <code>optional string methodName = 2;</code>
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <code>optional bytes data = 3;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <pre>
   *参数默认都为可选，如果没有赋值，那么接口中不会出现该参数，不会默认为null之类的
   * </pre>
   *
   * <code>optional string request_id = 4;</code>
   */
  java.lang.String getRequestId();
  /**
   * <pre>
   *参数默认都为可选，如果没有赋值，那么接口中不会出现该参数，不会默认为null之类的
   * </pre>
   *
   * <code>optional string request_id = 4;</code>
   */
  com.google.protobuf.ByteString
      getRequestIdBytes();
}
